MVCLibrary/Controllers/BooksController.cs
using MVCLibrary.Models;
using MVCLibrary.MyCart;
using MVCLibrary.Services;
using MVCLibrary.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCLibrary.Controllers
{
    public class BooksController : Controller
    {
        // GET: Books
        public ActionResult Index(Cart cart)
        {
            var cartBookViewModel = new CartBookViewModel();
            cartBookViewModel.cart = cart;
            using (var dbContext = new MvclibraryEntities())
            {
                var books = dbContext.Books.ToList();
                var bookvm = new List<BookViewModel>();
                foreach (var item in books)
                {
                    cartBookViewModel.BookViewModels.Add(new BookViewModel
                    {
                        Author = item.Author,
                        ISBN = item.ISBN,
                        status = item.Status,
                        NameCategory = dbContext.category.Where(c => c.Id == item.CategoryId).FirstOrDefault().Name,
                        Title = item.Title,
                        Id = item.Id
                    });
                }
                return View(cartBookViewModel);
            }
        }

        // GET: Books/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Books/Create
        public ActionResult Create()
        {
            using (var dbContext = new MvclibraryEntities())
            {
                var s = dbContext.category.ToList();
                var zvm = new BookAddViewModel();

                zvm.CategoryList = s.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name

                });

                return View(zvm);
            }
        }

        // POST: Books/Create
        [HttpPost]
        public ActionResult Create(BookAddViewModel newBook)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (var dbContext = new MvclibraryEntities())
                    {
                        if (dbContext.Books.Where(b => b.ISBN == newBook.ISBN).FirstOrDefault() != null)
                        {
                            ModelState.AddModelError("BookExist", "Książka o podanym ISBN juz istnieje");

                            var s = dbContext.category.ToList();

                            newBook.CategoryList = s.Select(x => new SelectListItem
                            {
                                Value = x.Id.ToString(),
                                Text = x.Name

                            });
                            return View(newBook);
                        }
                        var book = new Books
                        {
                            Author = newBook.Author,
                            Status = "Dostepna",
                            Title = newBook.Title,
                            ISBN = newBook.ISBN,
                            CategoryId = int.Parse(newBook.SelectedCategoryId),
                            DateCreatead = DateTime.Now
                        };
                        dbContext.Entry(book).State = EntityState.Added;
                        dbContext.SaveChanges();

                        return RedirectToAction("Index");
                    }

                }

                using (var dbContext = new MvclibraryEntities())
                {
                    var s = dbContext.category.ToList();

                    newBook.CategoryList = s.Select(x => new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.Name

                    });
                }
                return View(newBook);
            }
            catch
            {
                return View(newBook);
            }
        }

        // GET: Books/Edit/5
        public ActionResult Edit(int id)
        {
            using (var dbContext = new MvclibraryEntities())
            {
                var b = dbContext.Books.ToList();
                var editBooks = dbContext.Books.Where(c => c.Id == id).FirstOrDefault();

                var zvm = new BookAddViewModel
                {
                    Id = editBooks.Id,
                    SelectedCategoryId = editBooks.CategoryId.ToString(),
                    Author = editBooks.Author,
                    ISBN = editBooks.ISBN,
                    Title = editBooks.Title
                };

                zvm.CategoryList = dbContext.category.ToList().Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name

                });

                return View(zvm);
            }
        }

        // POST: Books/Edit/5
        [HttpPost]
        public ActionResult Edit(BookAddViewModel bvm)
        {
            try
            {
                // TODO: Add update logic here
                if (ModelState.IsValid)
                {
                    using (var dbContext = new MvclibraryEntities())
                    {
                        var books = dbContext.Books.ToList();
                        if (books.Where(b => b.ISBN == bvm.ISBN && b.Id != bvm.Id).FirstOrDefault() != null)
                        {
                            ModelState.AddModelError("BookExist", "Książka o podanym ISBN juz istnieje");
                            bvm.CategoryList = dbContext.category.ToList().Select(x => new SelectListItem
                            {
                                Value = x.Id.ToString(),
                                Text = x.Name

                            });
                            return View(bvm);
                        }
                        var editBook = dbContext.Books.Where(b => b.Id == bvm.Id).FirstOrDefault();

                        editBook.ISBN = bvm.ISBN;
                        editBook.Title = bvm.Title;
                        editBook.Author = bvm.Author;
                        editBook.CategoryId = int.Parse(bvm.SelectedCategoryId);
                        dbContext.Entry(editBook).State = EntityState.Modified;
                        dbContext.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                using (var dbContext = new MvclibraryEntities())
                {

                    bvm.CategoryList = dbContext.category.ToList().Select(x => new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.Name

                    });

                    return View(bvm);
                }
            }
            catch
            {
                return View();
            }
        }

        [Authorize]
        public ActionResult AddBookToCart(Cart cart, int id)
        {
            string url = this.Request.UrlReferrer.AbsolutePath;

            CartServic cartService = new CartServic();
            var cartViewModel = cartService.GetCartViewModel();
            if (cart.books.Count < 5)
            {
                if (cart.books.Find(b => b.Id == id) == null)
                {
                    using (var dbContext = new MvclibraryEntities())
                    {

                        var books = dbContext.Books.ToList();

                        var book = books.Where(b => b.Id == id).FirstOrDefault();
                        cart.books.Add(book);

                    }
                }
                else
                {
                    TempData["Message"] = "Podana książka znajduje się już w koszyku";
                    TempData["Status"] = "false";
                }
            }
            else
            {
                TempData["Message"] = "Nie można przekroczyć 5 książek w koszyku";
                TempData["Status"] = "false";
            }
            cartViewModel.cart = cart;
            return Redirect(url);
        }
        [Authorize]
        public ActionResult RemoveBook(Cart cart, int id)
        {
            string url = this.Request.UrlReferrer.AbsolutePath;

            CartServic cartService = new CartServic();
            var cartViewModel = cartService.GetCartViewModel();

            var book = cart.books.FirstOrDefault(b => b.Id == id);
            if (book != null)
            {
                cart.books.Remove(book);
            }

            cartViewModel.cart = cart;
            return Redirect(url);

        }
        [Authorize]
        public ActionResult ClearCart(Cart cart)
        {
            string url = this.Request.UrlReferrer.AbsolutePath;

            CartServic cartService = new CartServic();
            var cartViewModel = cartService.GetCartViewModel();
            cart.books.Clear();
            cartViewModel.cart = cart;
            return Redirect(url);

        }

        [Authorize]
        public ActionResult LendBooks(Cart cart)
        {
            string url = this.Request.UrlReferrer.AbsolutePath;

            CartServic cartService = new CartServic();
            var cartViewModel = cartService.GetCartViewModel();


            var userEmail = User.Identity.Name;

            using (var dbContext = new MvclibraryEntities())
            {
                var user = dbContext.User.Where(u => u.Email == userEmail).FirstOrDefault();

                var lends = dbContext.Lend.ToList();

                var userLends = lends.Where(l => l.UserId == user.Id && (l.State == "Odebrano" || l.State == "Na półce czytelnika")).ToList();

                if (userLends.Count + cart.books.Count <= user.BorrowLimit)
                {
                    foreach (var item in cart.books)
                    {
                        var lend = new Lend
                        {

MVCLibrary/Controllers/LendController.cs
using MVCLibrary.Models;
using MVCLibrary.Services;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCLibrary.Controllers
{
    public class LendController : Controller
    {
        // GET: Lend
        public ActionResult Index()
        {
            using (var dbContext = new MvclibraryEntities())
            {
                var lends = dbContext.Lend.ToList();

                var lendServicew = new LendService();

                var lendViewModel = lendServicew.GetViewModel(lends.OrderBy(o => o.DateBorrowed).ToList());
                return View(lendViewModel);
            }
        }

        public ActionResult WaitingBooks()
        {
            using (var dbContext = new MvclibraryEntities())
            {
                var lends = dbContext.Lend.Where(l => l.State == "Na półce czytelnika").ToList();

                var lendServicew = new LendService();

                var lendViewModel = lendServicew.GetViewModel(lends.OrderBy(o => o.DateBorrowed).ToList());
                return View("Index", lendViewModel);
            }
        }

        public ActionResult Lend()
        {
            using (var dbContext = new MvclibraryEntities())
            {
                var lends = dbContext.Lend.Where(l => l.State == "Odebrano").ToList();

                var lendServicew = new LendService();

                var lendViewModel = lendServicew.GetViewModel(lends.OrderBy(o => o.DateBorrowed).ToList());
                return View("Index", lendViewModel);
            }
        }

        public ActionResult Borrow(int id)
        {
            string url = this.Request.UrlReferrer.AbsolutePath;

            using (var dbContext = new MvclibraryEntities())
            {
                var lend = dbContext.Lend.Where(l => l.Id == id).FirstOrDefault();

                lend.State = "Odebrano";
                dbContext.Entry(lend).State = EntityState.Modified;
                dbContext.SaveChanges();
                return Redirect(url);
            }
        }
        public ActionResult Return(int id)
        {
            string url = this.Request.UrlReferrer.AbsolutePath;
            using (var dbContext = new MvclibraryEntities())
            {
                var lend = dbContext.Lend.Where(l => l.Id == id).FirstOrDefault();

                lend.State = "Zwrócono";
                dbContext.Entry(lend).State = EntityState.Modified;

                var book = dbContext.Books.Where(b => b.Id == lend.BookId).FirstOrDefault();
                book.Status = "Dostepna";
                dbContext.Entry(book).State = EntityState.Modified;

                dbContext.SaveChanges();
                return Redirect(url);
            }
        }

        [Authorize]
        public ActionResult UserLEnd()
        {
            using (var dbContext = new MvclibraryEntities())
            {
                var userEmail = User.Identity.Name;
                var user = dbContext.User.Where(u => u.Email == userEmail).FirstOrDefault();

                var lends = dbContext.Lend.Where(l => l.UserId == user.Id ).ToList();

                var lendServicew = new LendService();

                var lendViewModel = lendServicew.GetViewModel(lends.OrderBy(o => o.DateBorrowed).ToList());

                return View(lendViewModel);
            }
        }

        [Authorize]
        public ActionResult UserLEnd2()
        {
            using (var dbContext = new MvclibraryEntities())
            {
                var userEmail = User.Identity.Name;
                var user = dbContext.User.Where(u => u.Email == userEmail).FirstOrDefault();

                var lends = dbContext.Lend.Where(l => l.UserId == user.Id && l.State == "Na półce czytelnika").ToList();

                var lendServicew = new LendService();

                var lendViewModel = lendServicew.GetViewModel(lends.OrderBy(o => o.DateBorrowed).ToList());

                return View("UserLend",lendViewModel);
            }
        }
    }
}

MVCLibrary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MVC Library</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .libraryCart {
            background: url(../Images/shopingCart.png) no-repeat;
            background-size: 48px 48px;
            width: 48px;
            height: 48px;
            display: block;
            text-indent: -9999px;
        }
    </style>
</head>
<body ng-app="mvcLibrary">

    <div class="wrapper">
        <!-- Sidebar Holder -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>@Html.ActionLink("Biblioteka", "Index", "Home")</h3>
            </div>
            <ul class="list-unstyled components">

                @*@* KSIAZKI *@
                <li class="active">
                    <a href="#bookSubmenu" data-toggle="collapse" aria-expanded="false">Ksiazki</a>
                    <ul class="collapse list-unstyled" id="bookSubmenu">
                        <li>@Html.ActionLink("Ksiazki", "Index", "Books")</li>
                        @if (Request.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Worker")))
                        {
                            <li>@Html.ActionLink("Dodaj nową", "Create", "Books")</li>
                        }
                    </ul>
                </li>

                @* KATEGORIE *@

                <li>
                    <a href="#categorySubmenu" data-toggle="collapse" aria-expanded="false">Kategorie</a>
                    <ul class="collapse list-unstyled" id="categorySubmenu">
                        <li>@Html.ActionLink("Spis Kategorii", "Index", "Category")</li>
                        @if (Request.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Worker")))
                        {
                            <li>@Html.ActionLink("Dodaj nową", "Create", "Category")</li>
                        }
                    </ul>
                </li>

                @* CZYTELNICY *@
                @if (Request.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Worker")))
                {
                    <li>
                        <a href="#clientsSubmenu" data-toggle="collapse" aria-expanded="false">Czytelnicy</a>
                        <ul class="collapse list-unstyled" id="clientsSubmenu">
                            <li> @Html.ActionLink("Spis klientów", "Index", "User")</li>
                            <li> @Html.ActionLink("Niezweryfikowani klienci", "UsersToVerify", "User")</li>
                        </ul>
                    </li>
                }
                @*Wypożyczenia*@
                @if (Request.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Worker")))
                {
                    <li>
                        <a href="#lendsSubmenu" data-toggle="collapse" aria-expanded="false">Wypożyczenia</a>
                        <ul class="collapse list-unstyled" id="lendsSubmenu">
                            <li> @Html.ActionLink("Wszystkie wypożyczenia", "Index", "Lend")</li>
                            <li> @Html.ActionLink("Do odebrania", "WaitingBooks", "Lend")</li>
                            <li> @Html.ActionLink("Odebrane", "Lend", "Lend")</li>
                        </ul>
                    </li>
                }
                @*Pracownicy*@
                @if (Request.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Worker")))
                {
                    <li>
                        <a href="#workesSubmenu" data-toggle="collapse" aria-expanded="false">Pracownicy</a>
                        <ul class="collapse list-unstyled" id="workesSubmenu">
                            <li> @Html.ActionLink("Spis pracowników", "Workers", "User")</li>
                        </ul>
                    </li>
                }
                @if (Request.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Worker")))
                {
                    <li>
                        @Html.ActionLink("Wiadomość", "Create", "message")
                    </li>
                }
            </ul>
        </nav>

        <!-- Page Content Holder -->
        <div id="content" class="container col-lg-12">
            <nav class="navbar navbar-default">
                <div class="container-fluid">

                    <div class="navbar-header">
                        <button type="button" id="sidebarCollapse" class="navbar-btn">
                            <span></span>
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                    <!-- Zmiana jezyka-->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <!-- Login PartialView-->
                        @Html.Partial("_LoginPartial")
                        <!-- Jakies podstrony-->
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="@Url.Action("Index", "Books")">Książki</a></li>
                            <li><a href="@Url.Action("Index", "Category")">Kategoria</a></li>
                            @*<li><a href="#">Page</a></li>*@
                            <!-- Wozek do wypozyczenia -->
                            @if (Request.IsAuthenticated)
                            {
                                <li>
                                    @*@Html.ActionLink("Cart", "Index", "Books", null, new { @class = "libraryCart" })*@
                                    <a href="@Url.Action("Index", "Books")">
                                        <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> Koszyk
                                    </a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>

            <div class="container body-content">
                @RenderBody()
                <hr />

                <footer>
                    <p>&copy; @DateTime.Now.Year - MVC Library</p>
                </footer>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
                $(this).toggleClass('active');
            });
        });
    </script>
</body>
</html>