MVCLibrary/Models/History.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public string Word { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}

MVCLibrary/Controllers/BooksController.cs
using MVCLibrary.Models;
using MVCLibrary.MyCart;
using MVCLibrary.Services;
using MVCLibrary.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCLibrary.Controllers
{
    public class BooksController : Controller
    {
        // GET: Books
        public ActionResult Index(Cart cart)
        {
            var cartBookViewModel = new CartBookViewModel();
            cartBookViewModel.cart = cart;
            using (var dbContext = new MvclibraryEntities())
            {
                var books = dbContext.Books.ToList();
                var bookvm = new List<BookViewModel>();
                foreach (var item in books)
                {
                    cartBookViewModel.BookViewModels.Add(new BookViewModel
                    {
                        Author = item.Author,
                        ISBN = item.ISBN,
                        status = item.Status,
                        NameCategory = dbContext.category.Where(c => c.Id == item.CategoryId).FirstOrDefault().Name,
                        Title = item.Title,
                        Id = item.Id
                    });
                }
                return View(cartBookViewModel);
            }
        }

        // GET: Books/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Books/Create
        public ActionResult Create()
        {
            using (var dbContext = new MvclibraryEntities())
            {
                var s = dbContext.category.ToList();
                var zvm = new BookAddViewModel();

                zvm.CategoryList = s.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name

                });

                return View(zvm);
            }
        }

        // POST: Books/Create
        [HttpPost]
        public ActionResult Create(BookAddViewModel newBook)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (var dbContext = new MvclibraryEntities())
                    {
                        if (dbContext.Books.Where(b => b.ISBN == newBook.ISBN).FirstOrDefault() != null)
                        {
                            ModelState.AddModelError("BookExist", "Książka o podanym ISBN juz istnieje");

                            var s = dbContext.category.ToList();

                            newBook.CategoryList = s.Select(x => new SelectListItem
                            {
                                Value = x.Id.ToString(),
                                Text = x.Name

                            });
                            return View(newBook);
                        }
                        var book = new Books
                        {
                            Author = newBook.Author,
                            Status = "Dostepna",
                            Title = newBook.Title,
                            ISBN = newBook.ISBN,
                            CategoryId = int.Parse(newBook.SelectedCategoryId),
                            DateCreatead = DateTime.Now
                        };
                        dbContext.Entry(book).State = EntityState.Added;
                        dbContext.SaveChanges();

                        return RedirectToAction("Index");
                    }

                }

                using (var dbContext = new MvclibraryEntities())
                {
                    var s = dbContext.category.ToList();

                    newBook.CategoryList = s.Select(x => new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.Name

                    });
                }
                return View(newBook);
            }
            catch
            {
                return View(newBook);
            }
        }

        // GET: Books/Edit/5
        public ActionResult Edit(int id)
        {
            using (var dbContext = new MvclibraryEntities())
            {
                var b = dbContext.Books.ToList();
                var editBooks = dbContext.Books.Where(c => c.Id == id).FirstOrDefault();

                var zvm = new BookAddViewModel
                {
                    Id = editBooks.Id,
                    SelectedCategoryId = editBooks.CategoryId.ToString(),
                    Author = editBooks.Author,
                    ISBN = editBooks.ISBN,
                    Title = editBooks.Title
                };

                zvm.CategoryList = dbContext.category.ToList().Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name

                });

                return View(zvm);
            }
        }

        // POST: Books/Edit/5
        [HttpPost]
        public ActionResult Edit(BookAddViewModel bvm)
        {
            try
            {
                // TODO: Add update logic here
                if (ModelState.IsValid)
                {
                    using (var dbContext = new MvclibraryEntities())
                    {
                        var books = dbContext.Books.ToList();
                        if (books.Where(b => b.ISBN == bvm.ISBN && b.Id != bvm.Id).FirstOrDefault() != null)
                        {
                            ModelState.AddModelError("BookExist", "Książka o podanym ISBN juz istnieje");
                            bvm.CategoryList = dbContext.category.ToList().Select(x => new SelectListItem
                            {
                                Value = x.Id.ToString(),
                                Text = x.Name

                            });
                            return View(bvm);
                        }
                        var editBook = dbContext.Books.Where(b => b.Id == bvm.Id).FirstOrDefault();

                        editBook.ISBN = bvm.ISBN;
                        editBook.Title = bvm.Title;
                        editBook.Author = bvm.Author;
                        editBook.CategoryId = int.Parse(bvm.SelectedCategoryId);
                        dbContext.Entry(editBook).State = EntityState.Modified;
                        dbContext.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                using (var dbContext = new MvclibraryEntities())
                {

                    bvm.CategoryList = dbContext.category.ToList().Select(x => new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.Name

                    });

                    return View(bvm);
                }
            }
            catch
            {
                return View();
            }
        }

        [Authorize]
        public ActionResult AddBookToCart(Cart cart, int id)
        {
            string url = this.Request.UrlReferrer.AbsolutePath;

            CartServic cartService = new CartServic();
            var cartViewModel = cartService.GetCartViewModel();
            if (cart.books.Count < 5)
            {
                if (cart.books.Find(b => b.Id == id) == null)
                {
                    using (var dbContext = new MvclibraryEntities())
                    {

                        var books = dbContext.Books.ToList();

                        var book = books.Where(b => b.Id == id).FirstOrDefault();
                        cart.books.Add(book);

                    }
                }
                else
                {
                    TempData["Message"] = "Podana książka znajduje się już w koszyku";
                    TempData["Status"] = "false";
                }
            }
            else
            {
                TempData["Message"] = "Nie można przekroczyć 5 książek w koszyku";
                TempData["Status"] = "false";
            }
            cartViewModel.cart = cart;
            return Redirect(url);
        }
        [Authorize]
        public ActionResult RemoveBook(Cart cart, int id)
        {
            string url = this.Request.UrlReferrer.AbsolutePath;

            CartServic cartService = new CartServic();
            var cartViewModel = cartService.GetCartViewModel();

            var book = cart.books.FirstOrDefault(b => b.Id == id);
            if (book != null)
            {
                cart.books.Remove(book);
            }

            cartViewModel.cart = cart;
            return Redirect(url);

        }
        [Authorize]
        public ActionResult ClearCart(Cart cart)
        {
            string url = this.Request.UrlReferrer.AbsolutePath;

            CartServic cartService = new CartServic();
            var cartViewModel = cartService.GetCartViewModel();
            cart.books.Clear();
            cartViewModel.cart = cart;
            return Redirect(url);

        }

        [Authorize]
        public ActionResult LendBooks(Cart cart)
        {
            string url = this.Request.UrlReferrer.AbsolutePath;

            CartServic cartService = new CartServic();
            var cartViewModel = cartService.GetCartViewModel();


            var userEmail = User.Identity.Name;

            using (var dbContext = new MvclibraryEntities())
            {
                var user = dbContext.User.Where(u => u.Email == userEmail).FirstOrDefault();

                var lends = dbContext.Lend.ToList();

                var userLends = lends.Where(l => l.UserId == user.Id && (l.State == "Odebrano" || l.State == "Na półce czytelnika")).ToList();

                if (userLends.Count + cart.books.Count <= user.BorrowLimit)
                {
                    foreach (var item in cart.books)
                    {
                        var lend = new Lend
                        {

MVCLibrary/Controllers/HistoryController.cs
using MVCLibrary.Models;
using MVCLibrary.MyCart;
using MVCLibrary.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCLibrary.Controllers
{
    public class HistoryController : Controller
    {
        // GET: History
        [Authorize]
        public ActionResult Index(Cart cart)
        {
            using (var dbContext = new MvclibraryEntities())
            {
                var histroy = dbContext.History.ToList();

                var user = dbContext.User.Where(u => u.Email == User.Identity.Name).FirstOrDefault();
                var userHistory = histroy.Where(h => h.UserID == user.Id).ToList();

                var bookvm = new List<BookViewModel>();
                var bookse = dbContext.Books.ToList();

                var cartBookViewModel = new CartBookViewModel();
                cartBookViewModel.cart = cart;

                foreach (var h in userHistory)
                {
                    if (h.Word == null) h.Word = "";
                   var books= bookse.Where(b => b.ISBN.Contains(h.Word) || b.Title.Contains(h.Word) || b.Author.Contains(h.Word)).ToList();
                    foreach (var item in books)
                    {
                        cartBookViewModel.BookViewModels.Add(new BookViewModel
                        {
                            Author = item.Author,
                            ISBN = item.ISBN,
                            status = item.Status,
                            NameCategory = dbContext.category.Where(c => c.Id == item.CategoryId).FirstOrDefault().Name,
                            Title = item.Title,
                            Id = item.Id
                        });
                    }

                }

                return View(cartBookViewModel);
            }
        }
    }
}

MVCLibrary/Views/History/Index.cshtml
@model MVCLibrary.ViewModels.CartBookViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Historia</h2>

@if (TempData["Status"] != null)
{
    if (TempData["Status"].ToString() == "false" && TempData["Message"] != null)
    {
        <div class="alert alert-danger">
            <strong>Error!</strong>  @TempData["Message"].ToString()
        </div>
    }
    if (TempData["Status"].ToString() == "true" && TempData["Message"] != null)
    {
        <div class="alert alert-success">
            <strong>Success!</strong> @TempData["Message"].ToString()
        </div>
    }
}

<div class="table-responsive">
    @if (Model.cart != null)
    {
        if (Model.cart.books.Count != 0)
        {
            <table class="table">
                @foreach (var item in Model.cart.books)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Author)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ISBN)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Status)
                        </td>
                        <td>
                            @Html.ActionLink("Usuń", "RemoveBook", "Books", new { id = item.Id }, new { @class = "btn btn-danger" })
                        </td>
                    </tr>

                }
            </table>
            @Html.ActionLink("Wypożycz ksiązki", "LendBooks", "Books", null, new { @class = "btn btn-success" })
            @Html.ActionLink("Wyczyść koszyk", "ClearCart", "Books", null, new { @class = "btn btn-danger" })
        }
    }

    @using (Html.BeginForm("Search", "Books", new { @class = "form - inline" }, FormMethod.Post, new { encype = "multipart /form-data", runat = "server" }))
    {
        <input placeholder="Tytuł, Autor, ISBN" type="text" name="value" class="inputs-size-bigger edittext-width" />
        <input type="submit" class="btn btn-success" style="margin: 10px;" value="Szukaj" />
    }
    @if (Model.SerchWord != null && Request.IsAuthenticated)
    {
        @Html.ActionLink("Zapisz historie wyszukiwania", "History", "Books", new { value = Model.SerchWord }, null)
    }
    <hr />
    <table class="table">
        <thead>
            <tr>
                <th>
                    Tytuł
                </th>
                <th>
                    Autor
                </th>
                <th>
                    ISBN
                </th>
                <th>
                    Kategoria
                </th>
                <th>
                    Status
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.BookViewModels)
            {
                <tr class="form-group">
                    @using (Html.BeginForm("Edit", "Books", FormMethod.Post))
                    {
                        <td>
                            @Html.DisplayFor(modelItem => item.Title, new { @class = "form-control" })
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Author, new { @class = "form-control" })
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ISBN, new { @class = "form-control" })
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NameCategory, new { @class = "form-control" })
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.status, new { @class = "form-control" })
                        </td>
                        <td>
                            @if (Request.IsAuthenticated)
                            {
                                if (item.status == "Dostepna")
                                {
                                    @Html.ActionLink("Dodaj do koszyka", "AddBookToCart", "Books", new { id = item.Id }, new { @class = "btn btn-success" })
                                }
                            }
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div>

@Html.ActionLink("< Wróć do profilu", "Profile", "User", null, new { @class = "action-link" })